export default [
  {
    id: 1,
    title: "Frontend Developer Intern",
    company: "Devify",
    location: "Hyderabad",
    stipend: "₹10,000/month",
    duration: "4 months",
    description: "Work with React and Tailwind on production-grade UIs.",
    skills: ["React", "JavaScript", "Tailwind CSS"],
  },
  {
    id: 2,
    title: "ML Intern",
    company: "InnovateX",
    location: "Mumbai",
    stipend: "₹15,000/month",
    duration: "6 months",
    description: "Work on machine learning models and data preprocessing.",
    skills: ["Python", "TensorFlow", "Pandas"],
  },
  {
    id: 3,
    title: "Data Analyst Intern",
    company: "NextGen Solutions",
    location: "Delhi",
    stipend: "₹8,000/month",
    duration: "2 months",
    description: "Analyze data using SQL and Python, and create dashboards.",
    skills: ["SQL", "Python", "Tableau"],
  },
  {
    id: 4,
    title: "Frontend Developer Intern",
    company: "SoftBridge",
    location: "Bangalore",
    stipend: "₹10,000/month",
    duration: "6 months",
    description: "Work with React and Tailwind on production-grade UIs.",
    skills: ["React", "JavaScript", "Tailwind CSS"],
  },
  {
    id: 5,
    title: "QA Intern",
    company: "InnovateX",
    location: "Mumbai",
    stipend: "₹10,000/month",
    duration: "2 months",
    description: "Write and execute test cases for web applications.",
    skills: ["Test Cases", "Selenium", "Jest"],
  },
  {
    id: 6,
    title: "Cybersecurity Intern",
    company: "InnovateX",
    location: "Mumbai",
    stipend: "₹8,000/month",
    duration: "4 months",
    description: "Assist in monitoring and securing applications.",
    skills: ["Network Security", "Python", "Linux"],
  },
  {
    id: 7,
    title: "Full Stack Intern",
    company: "TechCorp",
    location: "Remote",
    stipend: "₹15,000/month",
    duration: "6 months",
    description: "Contribute to both frontend and backend development.",
    skills: ["React", "Node.js", "MongoDB"],
  },
  {
    id: 8,
    title: "Data Analyst Intern",
    company: "Devify",
    location: "Remote",
    stipend: "₹15,000/month",
    duration: "2 months",
    description: "Analyze data using SQL and Python, and create dashboards.",
    skills: ["SQL", "Python", "Tableau"],
  },
  {
    id: 9,
    title: "DevOps Intern",
    company: "BrightSoft",
    location: "Remote",
    stipend: "₹10,000/month",
    duration: "3 months",
    description: "Support CI/CD pipelines and cloud infrastructure.",
    skills: ["Docker", "AWS", "CI/CD"],
  },
  {
    id: 10,
    title: "UI/UX Intern",
    company: "NeoTech",
    location: "Remote",
    stipend: "₹15,000/month",
    duration: "4 months",
    description: "Research user behavior and design intuitive UI components.",
    skills: ["Figma", "Prototyping", "User Testing"],
  },
  {
    id: 11,
    title: "Cybersecurity Intern",
    company: "CodeCraft",
    location: "Delhi",
    stipend: "₹15,000/month",
    duration: "3 months",
    description: "Assist in monitoring and securing applications.",
    skills: ["Network Security", "Python", "Linux"],
  },
  {
    id: 12,
    title: "ML Intern",
    company: "NeoTech",
    location: "Mumbai",
    stipend: "₹10,000/month",
    duration: "6 months",
    description: "Work on machine learning models and data preprocessing.",
    skills: ["Python", "TensorFlow", "Pandas"],
  },
  {
    id: 13,
    title: "Data Analyst Intern",
    company: "SoftBridge",
    location: "Mumbai",
    stipend: "₹10,000/month",
    duration: "6 months",
    description: "Analyze data using SQL and Python, and create dashboards.",
    skills: ["SQL", "Python", "Tableau"],
  },
  {
    id: 14,
    title: "ML Intern",
    company: "TechCorp",
    location: "Delhi",
    stipend: "₹10,000/month",
    duration: "6 months",
    description: "Work on machine learning models and data preprocessing.",
    skills: ["Python", "TensorFlow", "Pandas"],
  },
  {
    id: 15,
    title: "QA Intern",
    company: "CloudSync",
    location: "Mumbai",
    stipend: "₹15,000/month",
    duration: "4 months",
    description: "Write and execute test cases for web applications.",
    skills: ["Test Cases", "Selenium", "Jest"],
  },
  {
    id: 16,
    title: "Cybersecurity Intern",
    company: "Devify",
    location: "Remote",
    stipend: "₹8,000/month",
    duration: "2 months",
    description: "Assist in monitoring and securing applications.",
    skills: ["Network Security", "Python", "Linux"],
  },
  {
    id: 17,
    title: "ML Intern",
    company: "Devify",
    location: "Remote",
    stipend: "₹10,000/month",
    duration: "3 months",
    description: "Work on machine learning models and data preprocessing.",
    skills: ["Python", "TensorFlow", "Pandas"],
  },
  {
    id: 18,
    title: "Backend Developer Intern",
    company: "InnovateX",
    location: "Remote",
    stipend: "₹8,000/month",
    duration: "2 months",
    description: "Build scalable APIs using Node.js and Express.",
    skills: ["Node.js", "Express", "MongoDB"],
  },
  {
    id: 19,
    title: "DevOps Intern",
    company: "NeoTech",
    location: "Hyderabad",
    stipend: "₹10,000/month",
    duration: "3 months",
    description: "Support CI/CD pipelines and cloud infrastructure.",
    skills: ["Docker", "AWS", "CI/CD"],
  },
  {
    id: 20,
    title: "Frontend Developer Intern",
    company: "CodeCraft",
    location: "Hyderabad",
    stipend: "₹12,000/month",
    duration: "2 months",
    description: "Work with React and Tailwind on production-grade UIs.",
    skills: ["React", "JavaScript", "Tailwind CSS"],
  },
  {
    id: 21,
    title: "QA Intern",
    company: "VisionWare",
    location: "Bangalore",
    stipend: "₹8,000/month",
    duration: "3 months",
    description: "Write and execute test cases for web applications.",
    skills: ["Test Cases", "Selenium", "Jest"],
  },
  {
    id: 22,
    title: "Data Analyst Intern",
    company: "TechCorp",
    location: "Bangalore",
    stipend: "₹15,000/month",
    duration: "2 months",
    description: "Analyze data using SQL and Python, and create dashboards.",
    skills: ["SQL", "Python", "Tableau"],
  },
  {
    id: 23,
    title: "Backend Developer Intern",
    company: "VisionWare",
    location: "Bangalore",
    stipend: "₹12,000/month",
    duration: "4 months",
    description: "Build scalable APIs using Node.js and Express.",
    skills: ["Node.js", "Express", "MongoDB"],
  },
  {
    id: 24,
    title: "Cybersecurity Intern",
    company: "SoftBridge",
    location: "Remote",
    stipend: "₹15,000/month",
    duration: "3 months",
    description: "Assist in monitoring and securing applications.",
    skills: ["Network Security", "Python", "Linux"],
  },
  {
    id: 25,
    title: "UI/UX Intern",
    company: "Devify",
    location: "Remote",
    stipend: "₹8,000/month",
    duration: "3 months",
    description: "Research user behavior and design intuitive UI components.",
    skills: ["Figma", "Prototyping", "User Testing"],
  },
  {
    id: 26,
    title: "Full Stack Intern",
    company: "TechCorp",
    location: "Remote",
    stipend: "₹8,000/month",
    duration: "4 months",
    description: "Contribute to both frontend and backend development.",
    skills: ["React", "Node.js", "MongoDB"],
  },
  {
    id: 27,
    title: "DevOps Intern",
    company: "Devify",
    location: "Delhi",
    stipend: "₹15,000/month",
    duration: "4 months",
    description: "Support CI/CD pipelines and cloud infrastructure.",
    skills: ["Docker", "AWS", "CI/CD"],
  },
  {
    id: 28,
    title: "Full Stack Intern",
    company: "TechCorp",
    location: "Bangalore",
    stipend: "₹10,000/month",
    duration: "2 months",
    description: "Contribute to both frontend and backend development.",
    skills: ["React", "Node.js", "MongoDB"],
  },
  {
    id: 29,
    title: "Cybersecurity Intern",
    company: "NeoTech",
    location: "Hyderabad",
    stipend: "₹15,000/month",
    duration: "6 months",
    description: "Assist in monitoring and securing applications.",
    skills: ["Network Security", "Python", "Linux"],
  },
  {
    id: 30,
    title: "DevOps Intern",
    company: "NextGen Solutions",
    location: "Mumbai",
    stipend: "₹10,000/month",
    duration: "3 months",
    description: "Support CI/CD pipelines and cloud infrastructure.",
    skills: ["Docker", "AWS", "CI/CD"],
  },
  {
    id: 31,
    title: "QA Intern",
    company: "TechCorp",
    location: "Hyderabad",
    stipend: "₹8,000/month",
    duration: "3 months",
    description: "Write and execute test cases for web applications.",
    skills: ["Test Cases", "Selenium", "Jest"],
  },
  {
    id: 32,
    title: "Product Design Intern",
    company: "CodeCraft",
    location: "Hyderabad",
    stipend: "₹10,000/month",
    duration: "2 months",
    description: "Design user-centric product interfaces and experiences.",
    skills: ["Figma", "Sketch", "User Research"],
  },
  {
    id: 33,
    title: "Frontend Developer Intern",
    company: "BrightSoft",
    location: "Delhi",
    stipend: "₹12,000/month",
    duration: "2 months",
    description: "Work with React and Tailwind on production-grade UIs.",
    skills: ["React", "JavaScript", "Tailwind CSS"],
  },
  {
    id: 34,
    title: "Backend Developer Intern",
    company: "NextGen Solutions",
    location: "Delhi",
    stipend: "₹8,000/month",
    duration: "6 months",
    description: "Build scalable APIs using Node.js and Express.",
    skills: ["Node.js", "Express", "MongoDB"],
  },
  {
    id: 35,
    title: "Full Stack Intern",
    company: "TechCorp",
    location: "Delhi",
    stipend: "₹8,000/month",
    duration: "2 months",
    description: "Contribute to both frontend and backend development.",
    skills: ["React", "Node.js", "MongoDB"],
  },
  {
    id: 36,
    title: "Backend Developer Intern",
    company: "BrightSoft",
    location: "Remote",
    stipend: "₹8,000/month",
    duration: "6 months",
    description: "Build scalable APIs using Node.js and Express.",
    skills: ["Node.js", "Express", "MongoDB"],
  },
  {
    id: 37,
    title: "UI/UX Intern",
    company: "CloudSync",
    location: "Bangalore",
    stipend: "₹15,000/month",
    duration: "4 months",
    description: "Research user behavior and design intuitive UI components.",
    skills: ["Figma", "Prototyping", "User Testing"],
  },
  {
    id: 38,
    title: "Frontend Developer Intern",
    company: "Devify",
    location: "Hyderabad",
    stipend: "₹8,000/month",
    duration: "6 months",
    description: "Work with React and Tailwind on production-grade UIs.",
    skills: ["React", "JavaScript", "Tailwind CSS"],
  },
  {
    id: 39,
    title: "Product Design Intern",
    company: "SoftBridge",
    location: "Remote",
    stipend: "₹15,000/month",
    duration: "4 months",
    description: "Design user-centric product interfaces and experiences.",
    skills: ["Figma", "Sketch", "User Research"],
  },
  {
    id: 40,
    title: "UI/UX Intern",
    company: "NextGen Solutions",
    location: "Delhi",
    stipend: "₹12,000/month",
    duration: "6 months",
    description: "Research user behavior and design intuitive UI components.",
    skills: ["Figma", "Prototyping", "User Testing"],
  },
  {
    id: 41,
    title: "Product Design Intern",
    company: "VisionWare",
    location: "Bangalore",
    stipend: "₹15,000/month",
    duration: "2 months",
    description: "Design user-centric product interfaces and experiences.",
    skills: ["Figma", "Sketch", "User Research"],
  },
  {
    id: 42,
    title: "UI/UX Intern",
    company: "NextGen Solutions",
    location: "Bangalore",
    stipend: "₹12,000/month",
    duration: "2 months",
    description: "Research user behavior and design intuitive UI components.",
    skills: ["Figma", "Prototyping", "User Testing"],
  },
  {
    id: 43,
    title: "Frontend Developer Intern",
    company: "SoftBridge",
    location: "Bangalore",
    stipend: "₹15,000/month",
    duration: "6 months",
    description: "Work with React and Tailwind on production-grade UIs.",
    skills: ["React", "JavaScript", "Tailwind CSS"],
  },
  {
    id: 44,
    title: "Data Analyst Intern",
    company: "InnovateX",
    location: "Remote",
    stipend: "₹10,000/month",
    duration: "2 months",
    description: "Analyze data using SQL and Python, and create dashboards.",
    skills: ["SQL", "Python", "Tableau"],
  },
  {
    id: 45,
    title: "QA Intern",
    company: "NextGen Solutions",
    location: "Bangalore",
    stipend: "₹12,000/month",
    duration: "4 months",
    description: "Write and execute test cases for web applications.",
    skills: ["Test Cases", "Selenium", "Jest"],
  },
  {
    id: 46,
    title: "Backend Developer Intern",
    company: "BrightSoft",
    location: "Bangalore",
    stipend: "₹10,000/month",
    duration: "3 months",
    description: "Build scalable APIs using Node.js and Express.",
    skills: ["Node.js", "Express", "MongoDB"],
  },
  {
    id: 47,
    title: "DevOps Intern",
    company: "BrightSoft",
    location: "Hyderabad",
    stipend: "₹10,000/month",
    duration: "6 months",
    description: "Support CI/CD pipelines and cloud infrastructure.",
    skills: ["Docker", "AWS", "CI/CD"],
  },
  {
    id: 48,
    title: "QA Intern",
    company: "BrightSoft",
    location: "Hyderabad",
    stipend: "₹8,000/month",
    duration: "2 months",
    description: "Write and execute test cases for web applications.",
    skills: ["Test Cases", "Selenium", "Jest"],
  },
  {
    id: 49,
    title: "Backend Developer Intern",
    company: "Devify",
    location: "Remote",
    stipend: "₹8,000/month",
    duration: "6 months",
    description: "Build scalable APIs using Node.js and Express.",
    skills: ["Node.js", "Express", "MongoDB"],
  },
  {
    id: 50,
    title: "Frontend Developer Intern",
    company: "Devify",
    location: "Bangalore",
    stipend: "₹10,000/month",
    duration: "3 months",
    description: "Work with React and Tailwind on production-grade UIs.",
    skills: ["React", "JavaScript", "Tailwind CSS"],
  },
];
